### ISSUE TITLE
导出 3dtiles 报错  2018版本

### ISSUE THREAD

**Issue by jmaxhu** [bimangle/forge-engine-samples#2]
![报错](https://user-images.githubusercontent.com/11311042/59338340-c2f28400-8d34-11e9-8063-fcaea10829b3.png)
尝试了几个模型都是这样，最简单的模型也一样报错。不知是什么原因？

**Comment by thorapp** [comment]
Engine SDK 的一些特性需要外部程序的支持，这些程序被放在一个被称为 “Home Folder” 的文件夹下，如果该文件夹不存在或内容不完整，就会报这个错误。您可以从 https://pan.baidu.com/s/1Gjxpvafbkta4grMnOkTYPg 下载 Engine RVT 安装版，装好之后 “Home Folder” 会放在默认位置下，网盘中也有一些文档，您可以参考下。

**Comment by bimangle** [comment]
Engine SDK 的一些特性需要外部程序的支持，这些程序被放在一个被称为 “Home Folder” 的文件夹下，如果该文件夹不存在或内容不完整，就会报这个错误。您可以从 https://pan.baidu.com/s/1Gjxpvafbkta4grMnOkTYPg 下载 Engine RVT 安装版，装好之后 “Home Folder” 会放在默认位置下，网盘中也有一些文档，您可以参考下。
