### ISSUE TITLE
Rebuild the solution Fail

### ISSUE THREAD

**Issue by Wingsky6** [bimangle/forge-engine-samples#4]
您好！Rebuild the solution Fail
180 errors 4 warnings
The type or namespace name 'XXX' could not be found 
请问如何解决呀？

**Comment by Wingsky6** [comment]
谢谢，已经解决了

**Comment by HAMZA-ROMAN** [comment]
@Wingsky6
Hi, i have same errors and wanings, can you  help me please , how you fixed hem ?
![bimangleErrors](https://user-images.githubusercontent.com/63560583/112336279-3e7cb580-8cbd-11eb-8970-43718fdf34f5.PNG)

**Comment by HAMZA-ROMAN** [comment]
hi, Errors and warnings solved 
1-https://forums.autodesk.com/t5/revit-api-forum/add-ins-help/m-p/6441862#M17376
2-https://forums.autodesk.com/t5/net/the-type-or-namespace-autodesk-could-not-be-found/td-p/5117774
3-https://github.com/bimangle/forge-engine-samples/issues/2

**Comment by bimangle** [comment]
1. Depending on the version you choose, use Visual Studio 2017 to open the corresponding solution file(*.sln)
2. Copy all nuget scripts from NugetCommands.txt, paste to VS2017 (Menu)Tools -> NuGet Package Manager -> Package Manager Console, and run these nuget scripts, this step will ensure the "BimAngle Engine SDK" available
3. Rebuild the solution
