### ISSUE TITLE
solution rebuild failed

### ISSUE THREAD

**Issue by ZZZZZZZZbbbbb** [bimangle/forge-engine-samples#5]
![image](https://user-images.githubusercontent.com/46518143/113086584-7aab9b00-9214-11eb-8adb-c4390e73f52f.png)
![image](https://user-images.githubusercontent.com/46518143/113086609-872ff380-9214-11eb-9e2c-3ec29de032e6.png)

help plz!

**Comment by bimangle** [comment]
1. Depending on the version you choose, use Visual Studio 2017 to open the corresponding solution file(*.sln)
2. Copy all nuget scripts from NugetCommands.txt, paste to VS2017 (Menu)Tools -> NuGet Package Manager -> Package Manager Console, and run these nuget scripts, this step will ensure the "BimAngle Engine SDK" available
3. Rebuild the solution
