### ISSUE TITLE
HOME folder of the engine sdk is invalid

### ISSUE THREAD

**Issue by jmcouffin** [bimangle/forge-engine-samples#8]
Hi, ice stuff here, 
I am hitting a wall:
After building, install is correct, but when launching an export to 3D tiles from the RVT basic sample I get the error : 
`The HOME folder of the engine sdk is invalid`

![image](https://user-images.githubusercontent.com/7872003/162236601-b78f249d-f7c6-47bd-b14d-2e647dada64a.png)

I do get this as an export but cannot see the building 
![image](https://user-images.githubusercontent.com/7872003/162236840-119833c5-6d33-466b-8399-9f69c5c70d24.png)

units?
georeferencing?
a way to find the building while in the viewer?

**Comment by Czzzzzzzzz** [comment]
Hey, buddy, I got the same problem. Did you solve it?

**Comment by jmcouffin** [comment]
Nope. No news.

**Comment by bimangle** [comment]
In addition to the basic functionality contained in the Engine SDK, there are additional features that are implemented by standalone applications.  These individual applications are stored in a Folder called the Home Folder along with some common files.  You can get this folder by installing the binary version, which you can then deploy to your users' computers.  

binary version link:
[For Autodesk Revit](http://fs3.bimangle.net/BimAngle_EngineExpress_RVT_v2022.04.14.zip)
[For Autodesk Navisworks](http://fs3.bimangle.net/BimAngle_EngineExpress_NW_v2022.04.28.zip)
[For Bentley MicroStation CE](http://fs3.bimangle.net/BimAngle_EngineExpress_NW_v2022.04.28.zip)

**Comment by bimangle** [comment]
The problem of not being able to see buildings is probably due to georeferencing.  You can put a screenshot of the export dialog and we'll analyze it. @jmcouffin

**Comment by jmcouffin** [comment]
> In addition to the basic functionality contained in the Engine SDK, there are additional features that are implemented by standalone applications. These individual applications are stored in a Folder called the Home Folder along with some common files. You can get this folder by installing the binary version, which you can then deploy to your users' computers.
> 
> binary version link: [For Autodesk Revit](http://fs3.bimangle.net/BimAngle_EngineExpress_RVT_v2022.04.14.zip) [For Autodesk Navisworks](http://fs3.bimangle.net/BimAngle_EngineExpress_NW_v2022.04.28.zip) [For Bentley MicroStation CE](http://fs3.bimangle.net/BimAngle_EngineExpress_NW_v2022.04.28.zip)

the binary version works great.
I will try to compile from the repo later on to try my own version
pretty quick translation process, impressive

**Comment by jmcouffin** [comment]
![image](https://user-images.githubusercontent.com/7872003/165915559-76ff7cb2-2201-43dd-84e8-5266b687e78f.png)

**Comment by jmcouffin** [comment]
is there a way to get the UI in english in the preview viewer? @bimangle

**Comment by bimangle** [comment]
The latest release version  already includes an English UI.
